spring:
  # 配置数据库
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/moon?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    # 地址
    host: 192.168.222.198
    # 端口，默认为6379
    port: 6379
    # 密码
    password: crmredis2021
    # 数据库索引
    database: 9
    # 连接超时时间
    connect-timeout: 10s

# 自定义日志目录 log4j2直接用${sys:LOG_PATH}读取
logging:
  file:
    path: ./application/logs