server:
  servlet:
    context-path: /moon
  port: 8081

spring:
  # 多环境配置切换
  profiles:
    active: dev

  #静态文件必需配
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates/,classpath:/static/,file:static/

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

mybatis-plus:
  # classpath* 加*可以扫描子模块的mapper
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.moon.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

# 开启日志
logging:
  config: classpath:logback-spring.xml
  level:
    com.baidu.mybatisplus.mapper: debug
    org.springframework.web:  debug