spring:
  # 配置数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/moon?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 自定义日志目录
logging:
  file:
    path: /opt/application/logs