server:
  servlet:
    context-path: /moon
  port: 8081

spring:
  # 多环境配置切换
  profiles:
    active: prod

  #静态文件必需配
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/


mybatis-plus:
  # classpath* 加*可以扫描子模块的mapper
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.moon.*.entity

# 开启日志
logging:
  config: classpath:logback-spring.xml
  level:
    com.baidu.mybatisplus.mapper: debug
    org.springframework.web:  debug