spring:
  profiles:
    active: dev

  #静态文件必需配
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/


mybatis-plus:
  # classpath* 加*可以扫描子模块的mapper
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.moon.*.entity